### PR TITLE
Telegram support

### PR DESCRIPTION
**Pull request by martini**
Hat leider etwas gedauert. 🙈

init-telegram

Es fehlen noch die Updates. Welche Idee hattest Du dazu?

### CODE REVIEW

**Comment by martini** [comment]
JFI: Generell müssen die Channels auch modularer werden. Da hat aber mit dieser Integration nichts direktes zu tun.

**Comment by schurig** [comment]
This is awesome!! Danke ❤️

**Comment by martini** [comment]
JFI: I already invested 6 more hours. Did a lot for refactoring (rails channel controller). Did not push it here because of so many changes.

**Comment by martini** [comment]
Splited all channels rails admin controller into separate files like https://github.com/zammad/zammad/blob/develop/app/controllers/channels_telegram_controller.rb Also did some refactoring on the admin channel coffee script controllers (now also separate files - like https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_channel/telegram.coffee).

By the way. Also merge your awesome telegram integration into develop branch! ❤️ You will get credits on release note for this awesome work!

**Pull request merged**
